POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmFrQGMuaW4iLCJleHAiOjE3NTI1NjI1MzUsInVzZXJJZCI6NH0.eS-qdtPLDSZHlWVTgWtDzOg-9x__OdvVo7JI0VIIqmA  
# token missing
# Authorization:        

{
  "name": "Data Team Meeting",
  "description": "Data Team Meeting - Using expired Token",
  "location": "Office - In person",
  "dateTime": "2025-03-28T19:34:00Z"
}

# {
#   "name": "Updated Event Name",
#   "description": "This event has been updated",
#   "location": "MS Teams - Online",
#   "dateTime": "2024-07-10T15:30:00Z",
# }

# {
#   "Id": 4,
#   "Name": "Demo Meeting 1",
#   "Description": "Demo Meeting 1",
#   "Location": "ZOOM - online",
#   "DateTime": "2025-03-02T16:11:00Z",
# }
