POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmFrQGMuaW4iLCJleHAiOjE3NTI1MDE3NDMsInVzZXJJZCI6NH0.aYhD-kIEuep34KhaAH5sVXlXCz5cEoory4Chm-dSFiI     
# token missing
# Authorization:        

{
  "name": "Dev Team Meeting",
  "description": "Dev Team Meeting",
  "location": "MS Teams - Online",
  "dateTime": "2025-06-03T19:34:00Z"
}

# {
#   "name": "Updated Event Name",
#   "description": "This event has been updated",
#   "location": "MS Teams - Online",
#   "dateTime": "2024-07-10T15:30:00Z",
# }

# {
#   "Id": 4,
#   "Name": "Demo Meeting 1",
#   "Description": "Demo Meeting 1",
#   "Location": "ZOOM - online",
#   "DateTime": "2025-03-02T16:11:00Z",
# }
