DELETE http://localhost:8080/event/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmFrQGMuaW4iLCJleHAiOjE3NTI1NjI1MzUsInVzZXJJZCI6NH0.eS-qdtPLDSZHlWVTgWtDzOg-9x__OdvVo7JI0VIIqmA
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldmFrQGMuaW4iLCJleHAiOjE3NTI1MDA3OTAsInVzZXJJZCI6NH0.Jts8qOsjwLDc-0ny7XJPxoFoP5HQiZyaB_ceJAInxE4